---
title: "ms_6"
author: "Tahmid Ahmed"
date: "4/3/2020"
output: html_document
---

```{r setup, include=FALSE, echo=FALSE}
library(readr)
library(tidyverse)
library(janitor)
library(reprex)
library(gt)
library(rvest)
library(xml2)
library(magrittr)
library(ggthemes)
library(plotly)
```

```{r kicker, echo=FALSE, include=FALSE}
# Downloading Kicker Data
url_kickers = "https://raw.githubusercontent.com/Nolanole/NFL-Weather-Project/master/Game_Logs_Kickers.csv"
url_kickers <- read_csv(url(url_kickers)) %>%
  clean_names()
url_kickers
```

```{r qb, echo=FALSE, include=FALSE}
# Downloading qb data
url_qb = "https://raw.githubusercontent.com/Nolanole/NFL-Weather-Project/master/Game_Logs_Quarterback.csv"
url_qb <- read_csv(url(url_qb))
```

```{r rb, include = FALSE, echo = FALSE}
# Downloading rb data
url_rb = "https://raw.githubusercontent.com/Nolanole/NFL-Weather-Project/master/Game_Logs_Runningback.csv"
url_rb <- read_csv(url(url_rb))
```

```{r weather, include = FALSE, echo = FALSE}
# downloading weather data
weather <- read_csv('raw-data/weather_20131231.csv',
                    na = c("undefined", "")) %>%
clean_names()
weather
```

```{r qbweather, include = FALSE, echo = FALSE}
# Qb and weather data merged
url_qbweather = "https://raw.githubusercontent.com/Nolanole/NFL-Weather-Project/master/QB_weather_cleaned.csv"
url_qbweather<- read_csv(url(url_qbweather))
url_qbweather
```

```{r weat, include = FALSE, echo = FALSE}
# weather in all games 
url_weathergit = "https://raw.githubusercontent.com/Nolanole/NFL-Weather-Project/master/all_games_weather.csv"
url_weathergit <- read_csv(url(url_weathergit))
```

```{r}
url_stadium = "https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-04/attendance.csv"
url_stadium <- read_csv(url(url_stadium))
```


```{r}
nba <- read_csv(url("https://raw.githubusercontent.com/ananhafez/NBA-Final-Project/master/NBA_App/Data/Seasons_stats_complete.csv"))
```

```{r}

giantsweather <- url_weathergit %>%
  filter(away == "New York Giants" | home == "New York Giants") %>%
  slice(495:627) %>%
  slice(-c(33:36, 117)) %>%
  mutate(id = 1:n()) %>%
  mutate(giants_points = ifelse(home == "New York Giants", score_home, score_away))


giants_stadium <- url_stadium %>%
  filter(team_name == "Giants" & (year == 2010 | year == 2011 | year == 2012 | year == 2013 | year == 2014 | year == 2015 | year == 2016 | year == 2017) & weekly_attendance != "NA") %>%
  mutate(id = 1:n())

```



```{r}
joineddata <- left_join(giantsweather, giants_stadium, by = "id")

attendance <- ggplot(joineddata, aes(avg_temp, weekly_attendance)) +
  geom_point() + geom_smooth(method = "lm") +
  theme_classic() +
  labs(title = "Weather's Impact on Attendance of Giants Games",
       subtitle = "Appears to be no correlation") +
  ylab("Attendance") +
  xlab("Temperature")
attendance

saveRDS(joineddata, file = "shiny/joined.rds")

```


```{r}
fitattendance <- lm(weekly_attendance ~ avg_temp, data = joineddata) 
joineddata %>%
  summarize(correlation = cor(avg_temp, weekly_attendance))
summary(fitattendance)

```


```{r}

giantsweather %>% ggplot(aes(date, giants_points)) + geom_point()
  


```




```{r EM, echo = FALSE}
# creating plot of weather impact on Tom Brady during Postseason
EM_regular <- url_qbweather %>%
filter(name == "Manning, Eli", season == "Regular Season")
EM_regularplot <- url_qbweather %>%
filter(name == "Manning, Eli", season == "Regular Season") %>%
  ggplot(aes(avg_temp, yards)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  theme_classic() +
  labs(title = "Weather Impact on Eli Manning's Yardage During the Regular Season") +
  labs(subtitle = "At start of career to 2017") +
  ylab("Yards") +
  xlab("Temperature")
EM_regularplot
```

```{r ggsavep1, message=FALSE}

ggsave(EM_regularplot, filename = "ms_6_shiny/EMreg.png")


```


```{r TB, echo = FALSE}
TB_postplot <- url_qbweather %>%
filter(name == "Brady, Tom", season == "Postseason") %>%
  ggplot(aes(avg_temp, comp_percent)) +
  geom_line() +
  theme_classic() +
  labs(title = "Weather Impact on Tom Brady's Accuracy During the Postseason") +
  labs(subtitle = "At start of career to 2017") +
  ylab("Completion Percentage") +
  xlab("Temperature")
```

```{r include=FALSE}

box_scores <- read_csv('raw-data/box_scores.csv')

```

```{r}
giants2012 <- box_scores %>%
  filter(visitor == "NY Giants" | home == "New York Giants") %>%
    filter(grepl("2012", date))
```

```{r}
url_rb %>%
  filter(Name == "Jacobs, Brandon" | Name == "Jennings, Rashad", Season == "Regular Season") %>%
  filter(grepl("2010|2011|2012|2013|2014|2015|2016", Year)) 
```





